### ISSUE TITLE
s3_media_upload non-AWS

### ISSUE THREAD

**Issue by HarHarLinks** [matrix-org/synapse-s3-storage-provider#34] opened 2020-04-04 19:58 UTC
The `s3_media_upload` script suffers from a handful shortcomings that stem from - in contrast to the `s3_storage_provider.py` module - not inheriting the homeserver config. 

Especially the trouble is that the default boto3 client instantiation somehow gets the region (from `.aws/config` default s3 maybe?) but not the complete URL/domain part - i.e. if you use something other that AWS, synapse will respect that but the upload script won't.

My suggestion is to instead of creating a custom `database.yaml` config file, to just read the `homeserver.yaml` instead (or worse, copy all relevant fields into it's own config).
Then parse everything relevant, e.g. `endpoint_url` to this:

https://github.com/matrix-org/synapse-s3-storage-provider/blob/a38b15b2a8588d734ebd43b9471aa9d6278feeb4/scripts/s3_media_upload#L435

**Comment by richvdh** [comment] 2020-05-13 14:25
> Especially the trouble is that the default boto3 client instantiation somehow gets the region (from .aws/config default s3 maybe?) but not the complete URL/domain part - i.e. if you use something other that AWS, synapse will respect that but the upload script won't.

this sounds like a duplicate of #25.

**Closed by richvdh** 2020-05-13 14:25 UTC
